# Generated by Django 6.0.4 on 2026-04-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofocusspec',
            name='af_contrast_detect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autofocusspec',
            name='af_coverage_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autofocusspec',
            name='af_touch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autofocusspec',
            name='face_detection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autofocusspec',
            name='insect_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autofocusspec',
            name='min_focus_ev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autofocusspec',
            name='vehicle_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='ae_bracketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='built_in_flash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='evf_coverage_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='evf_magnification',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='gps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='max_flash_sync',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='max_shutter_electronic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='max_shutter_mech',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='metering_center_weighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='metering_multi_segment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='metering_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='metering_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='screen_resolution_kdots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='screen_size_inches',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='timelapse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodyspec',
            name='wb_bracketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectivityspec',
            name='ethernet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectivityspec',
            name='flash_sync_port',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectivityspec',
            name='full_size_hdmi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensorspec',
            name='ibis_stops',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videospec',
            name='digital_is',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videospec',
            name='high_speed_video_fps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videospec',
            name='lens_breathing_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videospec',
            name='unlimited_recording',
            field=models.BooleanField(default=False),
        ),
    ]
