# Generated by Django 6.0.4 on 2026-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('focal_length', models.CharField(blank=True, max_length=100)),
                ('max_aperture', models.CharField(blank=True, max_length=20)),
                ('lens_type', models.CharField(blank=True, max_length=50)),
                ('is_popular', models.BooleanField(default=True)),
                ('official_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-is_popular', 'name'],
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='cons',
            field=models.TextField(blank=True, help_text='Newline-separated weaknesses'),
        ),
        migrations.AddField(
            model_name='camera',
            name='pros',
            field=models.TextField(blank=True, help_text="Newline-separated strengths, e.g. 'Excellent autofocus\nGreat dynamic range'"),
        ),
        migrations.AddField(
            model_name='camera',
            name='series',
            field=models.CharField(blank=True, help_text="e.g. 'EOS R', 'A7', 'X-T' — used to group related models", max_length=200),
        ),
    ]
