# Generated by Django 6.0.4 on 2026-04-10 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_series_pros_cons_lens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cameras/samples/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('taken_by', models.CharField(blank=True, max_length=200)),
                ('lens_name', models.CharField(blank=True, max_length=200)),
                ('focal_length', models.CharField(blank=True, max_length=50)),
                ('shutter_speed', models.CharField(blank=True, max_length=50)),
                ('aperture', models.CharField(blank=True, max_length=20)),
                ('iso', models.CharField(blank=True, max_length=20)),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_photos', to='catalog.camera')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
