# Generated by Django 6.0.4 on 2026-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_sample_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='mount',
            field=models.CharField(blank=True, choices=[('Sony E', 'Sony E (FE / APS-C)'), ('Canon RF', 'Canon RF'), ('Nikon Z', 'Nikon Z'), ('Fujifilm X', 'Fujifilm X'), ('Leica L', 'Leica L-Mount Alliance'), ('Micro Four Thirds', 'Micro Four Thirds (MFT)'), ('Fixed Lens', 'Fixed Lens (non-interchangeable)'), ('Canon EF', 'Canon EF (DSLR)'), ('Nikon F', 'Nikon F (DSLR)'), ('Sony A', 'Sony A (DSLR / Minolta)'), ('Pentax K', 'Pentax K'), ('Other', 'Other / Proprietary')], help_text="Interchangeable-lens mount or 'Fixed Lens' for compact cameras.", max_length=100),
        ),
        migrations.AlterField(
            model_name='lens',
            name='lens_type',
            field=models.CharField(blank=True, choices=[('prime', 'Prime'), ('zoom', 'Zoom'), ('macro', 'Macro'), ('tele', 'Telephoto'), ('wide', 'Wide Angle'), ('fisheye', 'Fisheye'), ('cine', 'Cinema / Cine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lens',
            name='mount',
            field=models.CharField(choices=[('Sony E', 'Sony E (FE / APS-C)'), ('Canon RF', 'Canon RF'), ('Nikon Z', 'Nikon Z'), ('Fujifilm X', 'Fujifilm X'), ('Leica L', 'Leica L-Mount Alliance'), ('Micro Four Thirds', 'Micro Four Thirds (MFT)'), ('Fixed Lens', 'Fixed Lens (non-interchangeable)'), ('Canon EF', 'Canon EF (DSLR)'), ('Nikon F', 'Nikon F (DSLR)'), ('Sony A', 'Sony A (DSLR / Minolta)'), ('Pentax K', 'Pentax K'), ('Other', 'Other / Proprietary')], db_index=True, max_length=100),
        ),
    ]
