# Generated by Django 6.0.4 on 2026-04-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutofocusSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_detect', models.BooleanField(default=False)),
                ('af_points', models.IntegerField(blank=True, null=True)),
                ('eye_af_human', models.BooleanField(default=False)),
                ('eye_af_animal', models.BooleanField(default=False)),
                ('subject_tracking', models.BooleanField(default=False)),
                ('burst_fps_mech', models.FloatField(blank=True, null=True)),
                ('burst_fps_electronic', models.FloatField(blank=True, null=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autofocus_spec', to='catalog.camera')),
            ],
        ),
        migrations.CreateModel(
            name='BodySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_g', models.IntegerField(blank=True, null=True)),
                ('width_mm', models.FloatField(blank=True, null=True)),
                ('height_mm', models.FloatField(blank=True, null=True)),
                ('depth_mm', models.FloatField(blank=True, null=True)),
                ('weather_sealed', models.BooleanField(default=False)),
                ('battery_shots_cipa', models.IntegerField(blank=True, null=True)),
                ('articulating_screen', models.BooleanField(default=False)),
                ('touchscreen', models.BooleanField(default=False)),
                ('evf', models.BooleanField(default=False)),
                ('evf_resolution', models.CharField(blank=True, max_length=100)),
                ('dual_card_slots', models.BooleanField(default=False)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_spec', to='catalog.camera')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectivitySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('usb_c', models.BooleanField(default=False)),
                ('usb_charging', models.BooleanField(default=False)),
                ('webcam_mode', models.BooleanField(default=False)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity_spec', to='catalog.camera')),
            ],
        ),
        migrations.CreateModel(
            name='SensorSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(blank=True, max_length=100)),
                ('sensor_format', models.CharField(blank=True, max_length=100)),
                ('sensor_width_mm', models.FloatField(blank=True, null=True)),
                ('sensor_height_mm', models.FloatField(blank=True, null=True)),
                ('effective_mp', models.FloatField(blank=True, null=True)),
                ('max_photo_resolution', models.CharField(blank=True, max_length=100)),
                ('native_iso_min', models.IntegerField(blank=True, null=True)),
                ('native_iso_max', models.IntegerField(blank=True, null=True)),
                ('extended_iso_min', models.IntegerField(blank=True, null=True)),
                ('extended_iso_max', models.IntegerField(blank=True, null=True)),
                ('ibis', models.BooleanField(default=False)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_spec', to='catalog.camera')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_video_resolution', models.CharField(blank=True, max_length=100)),
                ('max_4k_fps', models.IntegerField(blank=True, null=True)),
                ('max_fhd_fps', models.IntegerField(blank=True, null=True)),
                ('raw_video', models.BooleanField(default=False)),
                ('internal_10bit', models.BooleanField(default=False)),
                ('log_profiles', models.CharField(blank=True, max_length=200)),
                ('recording_limit_min', models.IntegerField(blank=True, null=True)),
                ('overheating_notes', models.TextField(blank=True)),
                ('mic_in', models.BooleanField(default=False)),
                ('headphone_out', models.BooleanField(default=False)),
                ('hdmi_type', models.CharField(blank=True, max_length=50)),
                ('usb_streaming', models.BooleanField(default=False)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_spec', to='catalog.camera')),
            ],
        ),
        migrations.CreateModel(
            name='SpecFieldSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_sources', to='catalog.camera')),
            ],
            options={
                'unique_together': {('camera', 'section', 'field_name')},
            },
        ),
    ]
