# Generated by Django 6.0.4 on 2026-04-09 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('official_website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('category', models.CharField(choices=[('mirrorless', 'Mirrorless'), ('dslr', 'DSLR'), ('compact', 'Compact'), ('cinema', 'Cinema'), ('action', 'Action')], default='mirrorless', max_length=20)),
                ('mount', models.CharField(blank=True, max_length=100)),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('rumored', 'Rumored')], default='active', max_length=20)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_price_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('short_summary', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='cameras/hero/')),
                ('official_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='catalog.brand')),
            ],
            options={
                'ordering': ['-release_date', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='CameraAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=300)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.camera')),
            ],
        ),
        migrations.CreateModel(
            name='CameraGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cameras/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.camera')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
